site_name: ipyvizzu-story
site_url: https://ipyvizzu-story.vizzuhq.com
copyright: Copyright &copy; 2022-2023 Vizzu

docs_dir: ../../docs

repo_url: https://github.com/vizzuhq/ipyvizzu-story
edit_uri: https://github.com/vizzuhq/ipyvizzu-story/edit/main/docs
use_directory_urls: false

theme:
  name: material
  palette:
    scheme: vizzu
  font:
    text: Roboto
    code: Roboto Mono
  logo: assets/logo-white.svg
  favicon: assets/favicon.svg
  custom_dir: ./overrides
  features:
    - toc.follow
    - search.suggest
    - search.highlight
    - navigation.top
    - navigation.footer

extra_css:
  - stylesheets/vizzu.css
  - stylesheets/highlight.css

extra_javascript:
  - javascripts/extlinks.js
  - //cdn.jsdelivr.net/gh/highlightjs/cdn-release@11.7/build/highlight.min.js
  - javascripts/highlight.js

extra:
  social:
    - icon: fontawesome/brands/slack
      name: Vizzu on Slack
      link: https://join.slack.com/t/vizzu-community/shared_invite/zt-w2nqhq44-2CCWL4o7qn2Ns1EFSf9kEg
    - icon: fontawesome/brands/twitter
      name: Vizzu on Twitter
      link: https://twitter.com/VizzuHQ
    - icon: fontawesome/brands/reddit
      name: Vizzu on Reddit
      link: https://www.reddit.com/user/VizzuHQ/?sort=top
    - icon: fontawesome/brands/github
      name: Vizzu on GitHub
      link: https://github.com/vizzuhq/

markdown_extensions:
  - pymdownx.tasklist:
      custom_checkbox: true
  - mdx_truly_sane_lists
  - attr_list
  - md_in_html

plugins:
  - search
  - section-index
  - literate-nav:
      implicit_index: true
  - autorefs
  - mkdocstrings:
      enable_inventory: true
      handlers:
        python:
          paths: [../../src]
          options:
            members_order: source
            show_root_heading: True
            show_root_members_full_path: True
            show_submodules: True
          import:
            - https://docs.python.org/3/objects.inv
  - gen-files:
      scripts:
        - gen_pages.py
        - gen_reference.py
  - coverage:
      page_name: coverage
      html_report_dir: tests/coverage
  - mkdocs-jupyter:
      # include: []
      ignore: ["demo/*.ipynb", "community/*.ipynb"]
      ignore_h1_titles: False
      include_source: True
      execute: True
      allow_errors: False
      kernel_name: .venv-ipyvizzu-story

nav:
  - Home: index.md
  - installation.md
  - Tutorial: tutorial/index.md
  - Examples:
      - examples/index.md
      - Basic example: examples/basic/basic.ipynb
      - Complex example: examples/complex/complex.ipynb
  - Code reference: reference/ipyvizzustory/
  - Environments:
      - environments/index.md
      - Notebooks:
          - environments/jupyter/index.md
          - Jupyter Notebook: environments/jupyter/jupyternotebook.md
          - environments/jupyter/colab.md
          - environments/jupyter/databricks.md
          - DataCamp: environments/jupyter/datacamp.md
          - environments/jupyter/deepnote.md
          - JupyterLab: environments/jupyter/jupyterlab.md
          - JupyterLite: environments/jupyter/jupyterlite.md
          - environments/jupyter/kaggle.md
          - environments/jupyter/mode.md
          - environments/jupyter/noteable.md
      - App platforms:
          - environments/platform/index.md
          - environments/streamlit.md
          - environments/panel.md
          - Mercury/mljar: environments/jupyter/mercury.md
          - Voilà: environments/jupyter/voila.md
      - BI tools:
          - environments/bi/index.md
          - environments/jupyter/mode.md
      - IDEs:
          - environments/ide/index.md
          - PyCharm: environments/jupyter/pycharm.md
          - VSCode Python: environments/jupyter/vscode.md
      - environments/python.md
  - Development:
      - dev/index.md
      - Contributing: CONTRIBUTING.md
      - Code of Conduct: CODE_OF_CONDUCT.md
      - Coverage report: coverage.md
  - License: LICENSE.md
