site_name: ipyvizzu-story
site_url: https://vizzuhq.github.io/ipyvizzu-story/

docs_dir: ../../docs

repo_url: https://github.com/vizzuhq/ipyvizzu-story
edit_uri: https://github.com/vizzuhq/ipyvizzu-story/edit/main/docs
use_directory_urls: false

theme:
  name: material
  custom_dir: ./overrides
  icon:
    logo: material/home

markdown_extensions:
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - mdx_truly_sane_lists

plugins:
  - search
  - autorefs
  - literate-nav
  - coverage:
      page_name: coverage
      html_report_dir: tests/coverage
  - section-index
  - mkdocstrings:
      handlers:
        python:
          paths: [../../src]
          options:
            members_order: source
            show_root_heading: True
            show_root_members_full_path: True
            show_submodules: True
  - mkdocs-jupyter:
      execute: True
      ignore: ["demo/*.ipynb", "community/*.ipynb"]
      kernel_name: .venv-ipyvizzu-story
      ignore_h1_titles: True
      include_source: True
  - gen-files:
      scripts:
        - gen_files.py

nav:
  - Home: index.md
  - installation.md
  - tutorial.md
  - Environments:
      - environments/index.md
      - Jupyter/IPython:
          - environments/jupyter/index.md
          - Jupyter Notebook: environments/jupyter/jupyternotebook.md
          - environments/jupyter/colab.md
          - environments/jupyter/databricks.md
          - DataCamp: environments/jupyter/datacamp.md
          - environments/jupyter/deepnote.md
          - JupyterLab: environments/jupyter/jupyterlab.md
          - JupyterLite: environments/jupyter/jupyterlite.md
          - environments/jupyter/kaggle.md
          - Mercury/mljar: environments/jupyter/mercury.md
          - environments/jupyter/mode.md
          - environments/jupyter/noteable.md
          - Voilà: environments/jupyter/voila.md
          - VSCode Python: environments/jupyter/vscode.md
      - environments/streamlit.md
      - environments/panel.md
      - environments/python.md
  - Examples:
      - examples/index.md
      - Basic example: examples/basic/basic.ipynb
      - Complex example: examples/complex/complex.ipynb
  - Reference: reference/ipyvizzustory/
  - Development:
      - Contributing: dev/CONTRIBUTING.md
      - Code of Conduct: dev/CODE_OF_CONDUCT.md
      - Coverage report: coverage.md
