name: CI

on:
  workflow_call:
    inputs:
      run_id:
        type: string
        required: true
        default: ${{ github.run_id }}

jobs:

  check_ci:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/cache@v3
      with:
        path: ./.venv-ipyvizzu-story
        key: venv-${{ inputs.run_id }}

    - uses: actions/cache@v3
      with:
        path: ./tests/coverage
        key: coverage-${{ inputs.run_id }}

    - name: Touch dev environment
      run: make touch-dev
          
    - name: Check format
      run: make check-format

    - name: Run pylint
      run: make lint
      
    - name: Check typing
      run: make check-typing

    - name: Run test
      run: make test
