name: CI-CD

on:
  release:
    types: [published]
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  init:
    uses: ./.github/workflows/init.yml
    with:
      run_id: ${{ github.run_id }}

  ci:
    uses: ./.github/workflows/ci.yml
    needs: init
    with:
      run_id: ${{ github.run_id }}

  doc_build:
    uses: ./.github/workflows/doc_build.yml
    needs: ci
    with:
      run_id: ${{ github.run_id }}

  doc_publish:
    uses: ./.github/workflows/doc_publish.yml
    needs: doc_build
    with:
      run_id: ${{ github.run_id }}

  release:
    uses: ./.github/workflows/release.yml
    secrets: inherit
    needs: doc_publish
    with:
      run_id: ${{ github.run_id }}
