name: Publish documentation

on:
  workflow_call:
    inputs:
      run_id:
        type: string
        required: true
        default: ${{ github.run_id }}

jobs:
  publish_doc:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: ./tests/coverage
          key: coverage-${{ inputs.run_id }}

      - name: Configure git
        run: |
          git config --global user.mail doc@github.com
          git config --global user.name doc

      - name: Switch to gh-pages branch
        run: |
          git branch -f gh-pages
          git switch gh-pages

      - uses: actions/cache@v3
        with:
          path: ./.venv-ipyvizzu-story
          key: venv-${{ inputs.run_id }}

      - name: Touch dev environment
        run: make touch-dev

      - name: Set Jupyter kernel
        run: make install-kernel

      - name: Build documentation
        run: make doc

      - name: Push to gh-pages branch
        run: |
          git add -f site
          git commit -am 'docs: update'
          git push -f origin gh-pages
        if: ( github.event_name == 'release' && github.event.action == 'published' ) || github.event_name == 'workflow_dispatch'

  deploy_doc:

    if: ( github.event_name == 'release' && github.event.action == 'published' ) || github.event_name == 'workflow_dispatch'
    
    needs: publish_doc
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
      
    permissions:
      id-token: write
      pages: write
      contents: read
    
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: gh-pages

      - name: Setup Pages
        uses: actions/configure-pages@v1

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'site'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@main
