name: Init

on:
  workflow_call:

jobs:

  init_dev:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: ./.venv-ipyvizzu-story
          key: venv-${{ github.run_id }}

      - name: Init dev environment
        run: make dev