name: Init

on:
  workflow_call:
    inputs:
      run_id:
        type: string
        required: true

jobs:

  init_dev:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: ./.venv_ipyvizzu_story
          key: venv-ipyvizzu-story-${{ inputs.run_id }}

      - name: Init dev environment
        run: make dev