name: Init

on:
  workflow_call:

jobs:

  init_dev:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: ./.venv_ipyvizzu_story
          key: venv-ipyvizzu-story-${{ github.run_id }}

      - uses: actions/cache@v3
        with:
          path: ./node_modules
          key: nodemodules-ipyvizzu-story-${{ github.run_id }}

      - name: Init dev environment
        run: make dev

      - name: Init dev-js environment
        run: make dev-js