name: Site

on:
  workflow_dispatch:
    inputs:
      run_id:
        type: string
        required: true

jobs:

  doc:
    uses: ./.github/workflows/doc.yml
    with:
      run_id: ${{ inputs.run_id }}
